/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CookieRouteImport } from './routes/cookie'
import { Route as PrezziRouteImport } from './routes/prezzi'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TerminiRouteImport } from './routes/termini'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfiloRouteImport } from './routes/_authenticated/profilo'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBandoIdRouteImport } from './routes/_authenticated/bando.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CookieRoute = CookieRouteImport.update({
  id: '/cookie',
  path: '/cookie',
  getParentRoute: () => rootRouteImport,
} as any)
const PrezziRoute = PrezziRouteImport.update({
  id: '/prezzi',
  path: '/prezzi',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminiRoute = TerminiRouteImport.update({
  id: '/termini',
  path: '/termini',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfiloRoute = AuthenticatedProfiloRouteImport.update({
  id: '/profilo',
  path: '/profilo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBandoIdRoute = AuthenticatedBandoIdRouteImport.update({
  id: '/bando/$id',
  path: '/bando/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cookie': typeof CookieRoute
  '/prezzi': typeof PrezziRoute
  '/privacy': typeof PrivacyRoute
  '/termini': typeof TerminiRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profilo': typeof AuthenticatedProfiloRoute
  '/bando/$id': typeof AuthenticatedBandoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cookie': typeof CookieRoute
  '/prezzi': typeof PrezziRoute
  '/privacy': typeof PrivacyRoute
  '/termini': typeof TerminiRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profilo': typeof AuthenticatedProfiloRoute
  '/bando/$id': typeof AuthenticatedBandoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cookie': typeof CookieRoute
  '/prezzi': typeof PrezziRoute
  '/privacy': typeof PrivacyRoute
  '/termini': typeof TerminiRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profilo': typeof AuthenticatedProfiloRoute
  '/_authenticated/bando/$id': typeof AuthenticatedBandoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/cookie' | '/prezzi' | '/privacy' | '/termini' | '/dashboard' | '/profilo' | '/bando/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/cookie' | '/prezzi' | '/privacy' | '/termini' | '/dashboard' | '/profilo' | '/bando/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cookie'
    | '/prezzi'
    | '/privacy'
    | '/termini'
    | '/_authenticated/dashboard'
    | '/_authenticated/profilo'
    | '/_authenticated/bando/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CookieRoute: typeof CookieRoute
  PrezziRoute: typeof PrezziRoute
  PrivacyRoute: typeof PrivacyRoute
  TerminiRoute: typeof TerminiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cookie': {
      id: '/cookie'
      path: '/cookie'
      fullPath: '/cookie'
      preLoaderRoute: typeof CookieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prezzi': {
      id: '/prezzi'
      path: '/prezzi'
      fullPath: '/prezzi'
      preLoaderRoute: typeof PrezziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termini': {
      id: '/termini'
      path: '/termini'
      fullPath: '/termini'
      preLoaderRoute: typeof TerminiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profilo': {
      id: '/_authenticated/profilo'
      path: '/profilo'
      fullPath: '/profilo'
      preLoaderRoute: typeof AuthenticatedProfiloRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bando/$id': {
      id: '/_authenticated/bando/$id'
      path: '/bando/$id'
      fullPath: '/bando/$id'
      preLoaderRoute: typeof AuthenticatedBandoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfiloRoute: typeof AuthenticatedProfiloRoute
  AuthenticatedBandoIdRoute: typeof AuthenticatedBandoIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfiloRoute: AuthenticatedProfiloRoute,
  AuthenticatedBandoIdRoute: AuthenticatedBandoIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CookieRoute: CookieRoute,
  PrezziRoute: PrezziRoute,
  PrivacyRoute: PrivacyRoute,
  TerminiRoute: TerminiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
